

const erro= async (req, res, next) => {
   
    next();
}
export default erro;